---

# if running this from cli use following command:
#  ansible-playbook main.yml --connection=local -e ansible_python_interpreter=/usr/bin/python3 --ask-sudo-pass --start-at-task="name of task" --check

#TODO: Update content organization to best practices:
# From: https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#alternative-directory-layout

# inventories/
#    prod/
#       hosts              # inventory file for prod servers
#       group_vars/
#          group1.yml      # assign vars to particular groups
#          group2.yml
#       host_vars/
#          hostname1.yml   # assign vars to particular systems
#          hostname2.yml
# 
#    test/
#       hosts              # inventory file for test
#       group_vars/
#          group1.yml      # assign vars to particular groups
#          group2.yml
#       host_vars/
#          stagehost1.yml  # assign vars to particular systems
#          stagehost2.yml
# 
# site.yml
# webservers.yml
# dbservers.yml
# 
# roles/
#     common/
#     webtier/
#     monitoring/
#     fooapp/

#TODO: Add molecule testing capabilities

#TODO: Add ansible.cfg:
  # From: https://robertdebock.nl/how-to-use-these-roles.html
  # [defaults]
  # roles_path=roles
  # retry_files_enabled=no
  # inventory=inventory


#TODO: create global .gitignore:
  # example: https://github.com/jdambron/dotfiles/blob/master/private_dot_gitignore_global

#TODO: create requirements.yml to use other roles:
  # https://github.com/gantsign/ansible-role-oh-my-zsh
  # https://github.com/Oefenweb/ansible-virtualbox
  # OR
  # https://github.com/alvistack/ansible-role-virtualbox
  # https://github.com/Oefenweb/ansible-vagrant
  # https://github.com/geerlingguy/ansible-role-pip
  # https://github.com/geerlingguy/ansible-role-docker


- hosts: localhost
# - hosts: all
  # gather_facts: yes
  # include_vars:
  #   - none
  # vars_files:
  #   - ../defaults/main.yml
  # vars_prompt:
  #   - name: "fzf_install_choice"
  #     prompt: "Choose installation method for fzf. Enter 'git' or 'bin'"
  #     default: "git"
  #     private: no
  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
      become: yes
      become_user: root
      when: ansible_bios_version == "VirtualBox"

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      become: yes
      become_user: root
      when: ansible_bios_version == "VirtualBox"

# DONE: Add password or figure out whats up in /etc/shadow for this user
    - name: Add sudoers users to wheel group
      user:
        name: cnmill05
        groups: wheel
        append: yes
        state: present
      become: yes
      become_user: root
      when: ansible_bios_version == "VirtualBox"

    - name: Install python for Ansible if needed
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-zipstream)
      become: yes
      changed_when: False
      when: ansible_bios_version != "VirtualBox"

    - name: Add PPAs
      apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: true
      become: yes
      with_items: "{{ ubuntu_ppas }}"

    - name:  Install required packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
        cache_valid_time: 3600
      become: yes
      with_items: "{{ ubuntu_required_packages }}"
      tags: install.packages

    - git_config:
        name: user.email
        scope: global
        value: 'git.20.trinity32@spamgourmet.com'

    - git_config:
        name: core.autocrlf
        scope: global
        value: false

    - git_config:
        name: user.name
        scope: global
        value: "girlandhercode"

    - name: Check for .oh-my-zsh directory
      stat:
        path: /home/{{ ansible_user_id }}/.oh-my-zsh
      register: oh_my_zsh_dir
      when: ansible_distribution == 'Ubuntu'
      # and 'i7-6700K' not in ansible_processor[0]


    - name: Clone oh-my-zsh repo
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: /home/{{ ansible_user_id }}/.oh-my-zsh
        depth: 1
      when: oh_my_zsh_dir.stat.exists == false and oh_my_zsh_dir.stat.isdir is not defined


# From https://github.com/DennisdeBest/bolt_provision
    - name: Ensure correct ownership and permissions of ~/.oh-my-zsh
      # become: no
      file:
        path: "/home/{{ ansible_user_id }}/.oh-my-zsh"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        # Prevent the cloned repository from having insecure permissions. Failing to do
        # so causes compinit() calls to fail with "command not found: compdef" errors
        # for users with insecure umasks (e.g., "002", allowing group writability).
        # mode: 'go-w'
        recurse: yes



######################################################
######################################################
########                                  ############
########    oh-my-zsh themes & plugins    ############
########                                  ############
######################################################
######################################################


    - name: Determine whether ~/.oh-my-zsh/custom/themes exists
      stat:
          path: /home/{{ ansible_user_id }}/.oh-my-zsh/custom/themes
      register: oh_my_zsh_themes_dir
      become: no

    - name: Create ~/.oh-my-zsh/custom/themes if it does not exist
      file:
        path: "/home/{{ ansible_user_id }}/.oh-my-zsh/custom/themes"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      when: oh_my_zsh_themes_dir.stat.isdir is defined and oh_my_zsh_themes_dir.stat.isdir


    - name: Determine state of lambda-mod
      stat:
        path: /home/{{ ansible_user_id }}/.oh-my-zsh/custom/themes/lambda-mod.zsh-theme
      register: lambda_mod_file

    - name: Download lambda-mod theme for oh-my-zsh
      get_url:
        url: https://raw.githubusercontent.com/halfo/lambda-mod-zsh-theme/master/lambda-mod.zsh-theme
        dest: /home/{{ ansible_user_id }}/.oh-my-zsh/custom/themes/lambda-mod.zsh-theme
      when:  lambda_mod_file.stat.exists == false







    - name: Determine whether ~/.oh-my-zsh/custom/plugins exists
      stat:
          path: /home/{{ ansible_user_id }}/.oh-my-zsh/custom/plugins
      register: oh_my_zsh_plugins_dir
      become: no

    - name: Create ~/.oh-my-zsh/custom/plugins if it does not exist
      file:
        path: "/home/{{ ansible_user_id }}/.oh-my-zsh/custom/plugins"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      when: oh_my_zsh_plugins_dir.stat.isdir is defined and oh_my_zsh_plugins_dir.stat.isdir

    - name: Determine state of fast-syntax-highlighting
      stat:
        path: /home/{{ ansible_user_id }}/.oh-my-zsh/custom/plugins/fast-syntax-highlighting
      register: fast_syntax_highlighting_dir

    - name: Download fast-syntax-highlighting for oh-my-zsh
      git:
        repo: https://github.com/zdharma/fast-syntax-highlighting.git
        dest: /home/{{ ansible_user_id }}/.oh-my-zsh/custom/plugins/fast-syntax-highlighting
        depth: 1
      when: fast_syntax_highlighting_dir.stat.isdir is defined and fast_syntax_highlighting_dir.stat.isdir == false






    - name: Determine whether ~/.zshrc exists
      stat:
          path: /home/{{ ansible_user_id }}/.zshrc
      register: zshrc_file
      become: no

    - name: Rename standard .zshrc
      command: mv /home/{{ ansible_user_id }}/.zshrc /home/{{ ansible_user_id }}/.zshrc.OLD
      args:
        creates: /home/{{ ansible_user_id }}/.zshrc.OLD
      when: zshrc_file.stat.exists == true

    - name: Determine whether ~/.zshrc.OLD exists
      stat:
          path: /home/{{ ansible_user_id }}/.zshrc.OLD
      register: zshrc_OLD_file
      become: no

    - name: Deploy .zshrc
      template:
        src: ../templates/zshrc.j2
        dest: /home/{{ ansible_user_id }}/.zshrc
      become: no
      when: zshrc_OLD_file.stat.exists == true or zshrc_file.stat.exists == false

    - name: Set zsh as default shell
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
      become: yes
      # when: ansible_lsb.codename == 'xenial'

    - name: Create 'Downloads' dir if it does not exist
      file:
        path: /home/{{ ansible_user_id }}/Downloads
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0700

    - name: Create 'Projects' dir if it does not exist
      file:
        path: /home/{{ ansible_user_id }}/Projects
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0700

#######################################################
##### Install fzf executable without bash binds etc
#######################################################

    # Based on info in: https://stackoverflow.com/a/26738019/2501386
    # - name: Get url for latest version of fzf for linux
    #   shell: curl -s https://api.github.com/repos/junegunn/fzf-bin/releases/latest | grep browser_download_url | grep 'linux_amd64.tgz' | cut -d '"' -f 4
    #   register: fzf_url
    #   when: ( fzf_install_choice == "bin" )

    # - name: Download fzf
    #   get_url:
    #     url: "{{ fzf_url.stdout }}"
    #     dest: /home/{{ ansible_user_id }}/Downloads/{{ fzf_url.stdout | basename }}
    #   when: ( fzf_install_choice == "bin" )

    # - name: Unpack fzf
    #   unarchive:
    #     copy: no
    #     src: /home/{{ ansible_user_id }}/Downloads/{{ fzf_url.stdout | basename }}
    #     dest: /home/{{ ansible_user_id }}/Downloads
    #   when: ( fzf_install_choice == "bin" )



######################################################
######################################################
############             OR             ##############
#####
##### Install fzf via 'git clone' to include extras
##### like keybinds in bash etc.
#####
######################################################
######################################################
######################################################

    # - name: Determine fzf install status
    #   shell: which fzf
    #   register: which_fzf
    #   become: no
    #   ignore_errors: true

    - name: Check for .fzf directory
      stat:
        path: /home/{{ ansible_user_id }}/.fzf
      register: fzf_dir

    - name: Clone fzf repo
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: /home/{{ ansible_user_id }}/.fzf
        depth: 1
      become: no
      when: fzf_dir.stat.exists == false and fzf_dir.stat.isdir is not defined

  # WONTDO: Implement expect for questions asked during fzf install

  # Need to escape special characters for regex
  # Info here: https://stackoverflow.com/a/39458575/2501386
  #  "Do you want to enable fuzzy auto-completion? ([y]/n)"
  #  "Do you want to enable key bindings? ([y]/n)"
  #  "Do you want to update your shell configuration files? ([y]/n)"

  #  Then source ~/.zshrc


# CRLF line ending removal from: https://stackoverflow.com/a/38284292/2501386
    # - name: Replace CRLF line endings when running under WSL
    #   replace:
    #     path: /home/{{ ansible_user_id }}.fzf/install
    #     regexp: "\r"
    #   when: ansible_distribution == 'Ubuntu' and 'i7-6700K' in ansible_processor[1]

    - name: Install fzf
      command: /home/{{ ansible_user_id }}/.fzf/install --all --64 --key-bindings --completion --update-rc --no-fish
      args:
        creates: /home/{{ ansible_user_id }}/.fzf/bin/fzf
      # when:  which_fzf.rc != 0

######################################################
##### Install Neovim plugin manager - 'vim-plug' - junegunn/vim-plug
######################################################

    - name: Ensure nvim conf dirs exist
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /home/{{ ansible_user_id }}/.local/share/nvim/site/autoload
        - /home/{{ ansible_user_id }}/.config/nvim

    - name: Determine whether vim-plug is installed
      stat:
          path: /home/{{ ansible_user_id }}/.local/share/nvim/site/autoload/plug.vim
      register: plug_vim_file
      become: no

    - name: Download and install 'vim-plug'
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: /home/{{ ansible_user_id }}/.local/share/nvim/site/autoload/plug.vim
      when: plug_vim_file.stat.exists == false

    - name: Determine whether ~/.config/nvim/init.vim exists
      stat:
          path: /home/{{ ansible_user_id }}/.config/nvim/init.vim
      register: init_vim_file
      become: no

    - debug:
        var: init_vim_file

    - name: Rename standard init.vim
      command: mv /home/{{ ansible_user_id }}/.config/nvim/init.vim /home/{{ ansible_user_id }}/init.vim.OLD
      args:
        creates: /home/{{ ansible_user_id }}/init.vim.OLD
      when: init_vim_file.stat.exists == true

    - name: Determine whether ~/init.vim.OLD exists
      stat:
          path: /home/{{ ansible_user_id }}/init.vim.OLD
      register: init_vim_OLD_file
      become: no

    - debug:
        var: init_vim_OLD_file

    - name: Deploy init.vim
      template:
        src: ../templates/init.vim.j2
        dest: /home/{{ ansible_user_id }}/.config/nvim/init.vim
      become: no
      when: init_vim_file.stat.exists == false or init_vim_OLD_file.stat.exists == true

    - name: Install nvim plugins
      command: nvim +PlugInstall +qall --headless
      changed_when: False


#####################################################
##### Manage ssh keys for WSL
#####################################################

# # # # Keys must either already exist or be created by # # # #

# https://github.com/girlandhercode/windows-development-environment

    # - name: Check for correct user's .ssh directory
    #   copy:
    #     src: /mnt/c/Users/{{ item }}/.ssh
    #     dest: /home/{{ ansible_user_id }}/
    #     # mode: 0700
    #     owner: "{{ ansible_user_id }}"
    #     group: "{{ ansible_user_id }}"
    #   with_items:
    #       - cnmill05
    #   when: (ansible_env.PATH | search('cnmill05')) and ('i7-6700K' in ansible_processor[0])

    # - name: Change mode of .ssh dir
    #   file:
    #     path: /home/{{ ansible_user_id }}/.ssh
    #     mode: 0700
    #   when: "'i7-6700K' in ansible_processor[0]"

    # - name: Change mode of all private ssh keys in .ssh
    #   file:
    #     path: "{{ item }}"
    #     mode: 0600
    #   with_fileglob:
    #     - '/home/{{ ansible_user_id }}/.ssh/*id_rsa*'
    #     - '/home/{{ ansible_user_id }}/.ssh/config'
    #   when: "'i7-6700K' in ansible_processor[0]"

    # - name: Change mode of all public keys in .ssh
    #   file:
    #     path: "{{ item }}"
    #     mode: 0644
    #   with_fileglob: '/home/{{ ansible_user_id }}/.ssh/*.pub'
    #   when: "'i7-6700K' in ansible_processor[0]"


#####################################################
#####################################################
#####################################################
#####
#####
##### Manage ssh keys for Ubuntu AND WSL -
#####    REFACTORED from above
#####
#####
#####################################################
#####################################################
#####################################################

    - name: Check for correct user's .ssh directory
      stat:
        path: /home/{{ ansible_user_id }}/.ssh
      register: ssh_dir
      when: ansible_distribution == 'Ubuntu'
      # and 'i7-6700K' not in ansible_processor[0]

    - name: Ensure correct mode of .ssh dir
      file:
        path: /home/{{ ansible_user_id }}/.ssh
        mode: 0700
        group: "{{ ansible_user_id }}"
        owner: "{{ ansible_user_id }}"
        state: directory
      when: ssh_dir.stat.exists and ansible_distribution == 'Ubuntu'
      #  and ('i7-6700K' not in ansible_processor[0])


    # - name: Get a list of existing keys
    #   # find:  
    #   #   paths: /home/{{ ansible_user_id }}/.ssh/
    #   #   patterns: '*_id_rsa'
    #   shell: ls /home/{{ ansible_user_id }}/.ssh
    #   register: priv_keys
    #   tags: file_check

    # - set_fact:
    #     keys: "{{ lookup('fileglob','/home/{{ ansible_user_id }}/.ssh/*_id_rsa', wantlist=true) | reject('search','.pub') | list }}"

    # - debug:
    #     var: keys[ {{ item }}] | basename
    #   with_sequence: start=0 end=3


    # - debug:
    #     var: "{{ item }}"
    #   with_indexed_tems: "{{ keys }}" 
    #   # with_sequence: start=0 end=3
    #   # register: existing_key_list
    #   tags: file_check


    - name: Generate ssh keys
      user:
        name: "{{ ansible_user_id }}"
        generate_ssh_key: yes
        ssh_key_file: '/home/{{ ansible_user_id }}/.ssh/{{ item }}_id_rsa'
      become: yes
      with_items:
        - "{{ user_ssh_priv_key_file_service_name }}"
      register: deploy_user_key_created
      when: ssh_dir.stat.exists and ansible_distribution == 'Ubuntu'
      # and 'i7-6700K' not in ansible_processor[0]

    - name: Change mode of all private ssh keys and config files in .ssh
      file:
        path: "{{ item }}"
        mode: 0600
      # with_items:
        # - "{{ user_ssh_priv_key_file_service_name }}"
        # - '/home/{{ ansible_user_id }}/.ssh/config'
      with_fileglob:
        - '/home/{{ ansible_user_id }}/.ssh/*id_rsa'
        - '/home/{{ ansible_user_id }}/.ssh/config'
      # when: item not in priv_keys.stdout_lines
      when: ssh_dir.stat.exists and ansible_distribution == 'Ubuntu'
      # and 'i7-6700K' not in ansible_processor[0]

    - name: Change mode of all public keys in .ssh
      file:
        path: "{{ item }}"
        mode: 0644
      with_fileglob: '/home/{{ ansible_user_id }}/.ssh/*.pub'
      when: ssh_dir.stat.exists and ansible_distribution == 'Ubuntu'
      # and 'i7-6700K' not in ansible_processor[0]